version: '3.4'
services:
  push-tf-secondary-1:
    container_name: "push-tf-secondary-1"
    hostname: "push-tf-secondary-1"
    tty: true
    image: eismcc/pushpy-start-tensorflow-gpu:latest
    expose:
      - '10001'
      - '11001'
      - '50001'
    env_file:
      - envs/push.env
    command: ["push_server", "/opt/pushpy/conf/secondary.yml"]
    network_mode: host
