version: '3.4'
services:
  push-tf-node-primary:
    container_name: "push-tf-node-primary"
    hostname: "push-tf-node"
    tty: true
    image: eismcc/push-${PUSH_DEPLOY_TYPE}-tensorflow-gpu:latest
    expose:
      - '10000'
      - '11000'
      - '50000'
    env_file:
      - ../envs/push.env
    volumes:
      - ../conf/primary.yml:/opt/pushpy/conf/push.conf.yml
      - $PUSH_HOME:/scm/push
      - $PUSH_APP_HOME/boot:/opt/pushpy/boot
    command: ["push_server", "/opt/pushpy/conf/push.conf.yml"]
    network_mode: host
