version: '3.4'
services:
  push-tf-node-primary:
    container_name: "push-tf-node-primary"
    hostname: "push-tf-node"
    tty: true
    image: eismcc/pushpy-start-tensorflow-gpu:latest
    expose:
      - '10000'
      - '11000'
      - '50000'
    command: ["push_server", "/opt/pushpy/conf/primary.yml"]
    network_mode: host
