version: '3.4'
services:
  push-tf-secondary-2:
    container_name: "push-tf-secondary-2"
    hostname: "push-tf-secondary-2"
    tty: true
    image: eismcc/pushpy-start-tensorflow-gpu:latest
    expose:
      - '10002'
      - '11002'
      - '50002'
    command: ["push_server", "/opt/pushpy/conf/secondary.yml"]
    network_mode: host
